# Linear Algebra
## Variables and arithmetic

In [26]:
# Basic linear expression

a = 3
b = 10
a + b * 2

23

In [27]:
# Checking with different print option

charos = 17

print( charos * b + 1 )
print( charos**b )

171
2015993900449


In [29]:
# Text + numeric types in Python

greeting = 'Hello my name is '
name = 'Charos'
age = 10

print(greeting + name + '!')
print('I am ' + str(age) + ' years old.')

Hello my name is Charos!
I am 10 years old.


In [30]:
# Small assigment! 

name = 'Charos'
age = 10

print('My name is ' + name + '. I am now ' + str(age) + ' years old, and in 6 years I\'ll be ' + str(age + 6) + ' years old.')

My name is Charos. I am now 10 years old, and in 6 years I'll be 16 years old.


## The numpy module

In [32]:
numlist = [1, 2, 3, 4, 4]
numlist

[1, 2, 3, 4, 4]

In [34]:
#testing absolute value
abs(-5)

5

In [36]:
import numpy as np

np.mean(numlist)
np.sqrt(4)

2.0

In [42]:
np.linspace(1, 10, 25)

funout = np.linspace(1, 10, 25)
funout

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [ ]:
# Assigment!

# 1) Create a list of 15 numbers from 4 to 100
# 2) Round those numbers to the nearest integer, and store in another variable
# 3) print out #2 
# 4) print out square root of each number in the list

In [44]:
# 1) Create a list of 15 numbers from 4 to 100

np.linspace(4, 100, 15)
assigment = np.linspace(4, 100, 15)

In [46]:
# 2) Round those numbers to the nearest integer, and store in another variable

np.rint(assigment)
roundedAssigment = np.rint(assigment)

In [48]:
# 3) print out #2 

roundedAssigment

array([  4.,  11.,  18.,  25.,  31.,  38.,  45.,  52.,  59.,  66.,  73.,
        79.,  86.,  93., 100.])

In [49]:
# 4) print out square root of each number in the list

np.sqrt(roundedAssigment)

array([ 2.        ,  3.31662479,  4.24264069,  5.        ,  5.56776436,
        6.164414  ,  6.70820393,  7.21110255,  7.68114575,  8.1240384 ,
        8.54400375,  8.88819442,  9.2736185 ,  9.64365076, 10.        ])